LOAD DATA
INFILE 'empleados.csv'
APPEND INTO TABLE empleado
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    EMP_ID INTEGER EXTERNAL,
    TIPIDE_ID INTEGER EXTERNAL,
    EMP_CODIGO_IDENTIFICACION CHAR,
    EMP_NOMBRE CHAR,
    EMP_APELLIDO CHAR,
    EMP_FECHA_NACIMIENTO DATE "MM/DD/YYYY",
    EMP_GENERO CHAR
)