LOAD DATA
INFILE 'posiciones.csv'
APPEND INTO TABLE posicion
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    POS_ID INTEGER EXTERNAL,
    JEFE_ID INTEGER EXTERNAL,
    SED_ID INTEGER EXTERNAL,
    PERCAR_ID INTEGER EXTERNAL,
    AREA_ID INTEGER EXTERNAL,
    POS_CATEGORIA INTEGER EXTERNAL,
    POS_LIMITE_PLAZAS INTEGER EXTERNAL
)