LOAD DATA
INFILE 'posicion_contrato.csv'
APPEND INTO TABLE posicion_contrato
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CON_ID INTEGER EXTERNAL,
    POS_ID INTEGER EXTERNAL,
    POSCON_FECHA_INICIO DATE "MM/DD/YYYY",
    POSCON_FECHA_FIN DATE "MM/DD/YYYY",
    POSCON_CARACTERISTICA CHAR
)