LOAD DATA
INFILE 'seguridadsocial_contrato_1.csv'
APPEND INTO TABLE contrato_seguridadsocial
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CON_ID INTEGER EXTERNAL,
    SEGSOC_ID INTEGER EXTERNAL,
    CONSEG_FECHA_INICIO DATE "MM/DD/YYYY",
    CONSEG_CODIGO_DOCUMENTO CHAR,
    CONSEG_FECHA_FINALIZACION DATE "MM/DD/YYYY"
)